// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parameters.proto

#include "parameters.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace demo {
namespace parameters {
PROTOBUF_CONSTEXPR SubmitResult::SubmitResult(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.logs_)*/{}
  , /*decltype(_impl_.status_data_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SubmitResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SubmitResultDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SubmitResultDefaultTypeInternal() {}
  union {
    SubmitResult _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SubmitResultDefaultTypeInternal _SubmitResult_default_instance_;
}  // namespace parameters
}  // namespace demo
static ::_pb::Metadata file_level_metadata_parameters_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_parameters_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_parameters_2eproto = nullptr;

const uint32_t TableStruct_parameters_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::demo::parameters::SubmitResult, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::demo::parameters::SubmitResult, _impl_.status_data_),
  PROTOBUF_FIELD_OFFSET(::demo::parameters::SubmitResult, _impl_.logs_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::demo::parameters::SubmitResult)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::demo::parameters::_SubmitResult_default_instance_._instance,
};

const char descriptor_table_protodef_parameters_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020parameters.proto\022\017demo.parameters\032\013bas"
  "ic.proto\"H\n\014SubmitResult\022\023\n\013status_data\030"
  "\001 \001(\r\022#\n\004logs\030\002 \003(\0132\025.demo.basic.ResultL"
  "ogb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_parameters_2eproto_deps[1] = {
  &::descriptor_table_basic_2eproto,
};
static ::_pbi::once_flag descriptor_table_parameters_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_parameters_2eproto = {
    false, false, 130, descriptor_table_protodef_parameters_2eproto,
    "parameters.proto",
    &descriptor_table_parameters_2eproto_once, descriptor_table_parameters_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_parameters_2eproto::offsets,
    file_level_metadata_parameters_2eproto, file_level_enum_descriptors_parameters_2eproto,
    file_level_service_descriptors_parameters_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_parameters_2eproto_getter() {
  return &descriptor_table_parameters_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_parameters_2eproto(&descriptor_table_parameters_2eproto);
namespace demo {
namespace parameters {

// ===================================================================

class SubmitResult::_Internal {
 public:
};

void SubmitResult::clear_logs() {
  _impl_.logs_.Clear();
}
SubmitResult::SubmitResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:demo.parameters.SubmitResult)
}
SubmitResult::SubmitResult(const SubmitResult& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SubmitResult* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.logs_){from._impl_.logs_}
    , decltype(_impl_.status_data_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.status_data_ = from._impl_.status_data_;
  // @@protoc_insertion_point(copy_constructor:demo.parameters.SubmitResult)
}

inline void SubmitResult::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.logs_){arena}
    , decltype(_impl_.status_data_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SubmitResult::~SubmitResult() {
  // @@protoc_insertion_point(destructor:demo.parameters.SubmitResult)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SubmitResult::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.logs_.~RepeatedPtrField();
}

void SubmitResult::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SubmitResult::Clear() {
// @@protoc_insertion_point(message_clear_start:demo.parameters.SubmitResult)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.logs_.Clear();
  _impl_.status_data_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SubmitResult::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 status_data = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.status_data_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .demo.basic.ResultLog logs = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_logs(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SubmitResult::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:demo.parameters.SubmitResult)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 status_data = 1;
  if (this->_internal_status_data() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_status_data(), target);
  }

  // repeated .demo.basic.ResultLog logs = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_logs_size()); i < n; i++) {
    const auto& repfield = this->_internal_logs(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:demo.parameters.SubmitResult)
  return target;
}

size_t SubmitResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:demo.parameters.SubmitResult)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .demo.basic.ResultLog logs = 2;
  total_size += 1UL * this->_internal_logs_size();
  for (const auto& msg : this->_impl_.logs_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint32 status_data = 1;
  if (this->_internal_status_data() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_status_data());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SubmitResult::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SubmitResult::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SubmitResult::GetClassData() const { return &_class_data_; }


void SubmitResult::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SubmitResult*>(&to_msg);
  auto& from = static_cast<const SubmitResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:demo.parameters.SubmitResult)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.logs_.MergeFrom(from._impl_.logs_);
  if (from._internal_status_data() != 0) {
    _this->_internal_set_status_data(from._internal_status_data());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SubmitResult::CopyFrom(const SubmitResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:demo.parameters.SubmitResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SubmitResult::IsInitialized() const {
  return true;
}

void SubmitResult::InternalSwap(SubmitResult* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.logs_.InternalSwap(&other->_impl_.logs_);
  swap(_impl_.status_data_, other->_impl_.status_data_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SubmitResult::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_parameters_2eproto_getter, &descriptor_table_parameters_2eproto_once,
      file_level_metadata_parameters_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace parameters
}  // namespace demo
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::demo::parameters::SubmitResult*
Arena::CreateMaybeMessage< ::demo::parameters::SubmitResult >(Arena* arena) {
  return Arena::CreateMessageInternal< ::demo::parameters::SubmitResult >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
